### ISSUE TITLE
如何修改secret flow控制台的logo以及重新打包

### ISSUE THREAD

**Issue by WillLei1991** [secretflow/secretpad-frontend#1]
![image](https://github.com/secretflow/secretpad-frontend/assets/48860136/b2d3c86e-5431-4f93-8bc5-f75d5495af3f)
如题，需要修改控制台的logo和整体色调。可以基于 https://github.com/secretflow/secretpad-frontend 代码拉一个自己的单独分支，找到对应的代码并修改，主要问题在于修改完成后如何重新打安装包？麻烦提供对应的教程，谢谢。
![image](https://github.com/secretflow/secretpad-frontend/assets/48860136/c4c38225-2bfd-4126-a9e6-b33a0475f1ec)

**Comment by bigdadel** [comment]
https://github.com/secretflow/secretpad-frontend/blob/main/apps/docs/docs/dev-doc/build.md
可以按照这个文档里的流程操作一下哈，之后需要重新部署整个后端工程。

**Comment by bigdadel** [comment]
另外构建出 `dist` 文件下的产物需要放在 https://github.com/secretflow/secretpad/tree/main 项目的 `/secretpad-web/src/main/resources/static` 目录下（新建），之后运行 secretpad 的 `bash ./scripts/build.sh` 命令重新构建镜像（注意不是 `make build`，`make build` 会拉取官方 release 的前端产物构建镜像）。

后续我们会对这部分处理方式进行优化。
