### ISSUE TITLE
最新的 release 0.3.0b0 登录页面登录后提示登录成功，但是一直在登录页无法跳转

### ISSUE THREAD

**Issue by changhr2013** [secretflow/secretpad-frontend#10]
### Description 描述

<img width="1792" alt="image" src="https://github.com/secretflow/secretpad-frontend/assets/8073367/156bbc65-8bbb-4b44-a096-a9c275e39849">
如图，提示登录成功会刷回登录页，无法跳转。

### Steps to reproduce 复现步骤

使用 secretpad 仓库 master 分支最新代码 build 脚本构建的 jar，拉取的是 v0.3.0b0 tag 的 tar。

**Comment by changhr2013** [comment]
似乎是我自定义的镜像问题，忽略。

**Comment by yinrouni** [comment]
hi, 
目前新版本(v0.4.0b0) secretpad & secretpad-frontend已发布，支持 P2P 部署架构，欢迎体验。如果希望通过build 脚本构建之前v0.3.0b0版本，辛苦手动适配一下对应前端版本[v0.3.0b1](https://github.com/secretflow/secretpad-frontend/releases/tag/v0.3.0b1)。后续我们将对这一问题进行优化。

部署步骤请参考： dist 文件下的产物需要放在 https://github.com/secretflow/secretpad/tree/main 项目的 /secretpad-web/src/main/resources/static 目录下（新建），之后运行 secretpad 的 bash ./scripts/build.sh 命令重新构建镜像（注意不是 make build，make build 会拉取官方 release 的前端产物构建镜像）。

thx
