### ISSUE TITLE
[Bug]: qiankun复用隐语系统作为子应用会导致报错

### ISSUE THREAD

**Issue by tianyunzhu** [secretflow/secretpad-frontend#12]
### Description 描述

当我们使用这个系统作为qiankun的子应用，在config.js文档我们会配置qiankun的一些信息，如果只是作为子应用 会这样写
 plugins: ['@umijs/plugins/dist/qiankun'],//这段代码是为了引用插件，因为umijs4似乎并不支持插件自动引入
  qiankun: {
    slave: {},
  },
  },
当我们写完这个配置之后 会报错 说package.json文件缺少name 于是我来到了apps\platform\package.json文件(是的我将这个platform作为我的子应用来使用)，然后这个时候我选择去添加这个name:"passport" 于是代码正常运行了 此时访问隐语系统 浏览器地址为http://localhost:8000/passport/login 登录页面 然后输入账号密码 即使登录成功也会调回登录页面 于是我对bug进行排查 发现在某一瞬间 地址是http://localhost:8000/passport/passport/edge/* 然后路由管理器判定这是一个错乱的路由 于是调回登录页面 
所以我非常好奇 为什么在添加name属性后浏览器会自动加上这个属性而且还不止加一次

### Steps to reproduce 复现步骤
想要复现这个bug还可以通过给config.js加一个base属性 然后正常访问 也会出现连加2次base导致路由错乱的问题
_No response_

**Comment by yinrouni** [comment]
关于qiankun的配置可以参考 
https://umijs.org/docs/max/micro-frontend#%E5%BC%95%E5%85%A5%E5%AD%90%E5%BA%94%E7%94%A8

微前端架构我们正在验证中，后续会在开发文档dev-doc中补充实践示例。

**Comment by Chrisdehe** [comment]
@tianyunzhu ，请问咱们的场景是怎么样呢，如果方便的话可以添加隐语技术支持沟通下（secretflow02）

**Comment by yinrouni** [comment]
Hi,
在最新的版本里我们修复了路由问题并补充了微前端（qiankun）集成示例文档 
https://secretflow.github.io/secretpad-frontend/dev-doc/qiankun
可以基于v0.6.0b0尝试一下，thx
