### ISSUE TITLE
[Bug]: pnpm build 报错

### ISSUE THREAD

**Issue by littlegirlpppp** [secretflow/secretpad-frontend#14]
### Description 描述

pnpm build 报错 版本0.5.0最新版本

### Steps to reproduce 复现步骤

1 pnpm dev 调试模式正常
2 pnpm build 报错

### Expected behavior 期望效果

修复pnpm build

### Other information 其它信息

PS D:\sunbo\Haier\src\secretflow\frontend\secretpad-frontend> pnpm build

> @ build D:\sunbo\Haier\src\secretflow\frontend\secretpad-frontend
> nx run-many --target=build --nx-bail=true

    √  nx run secretpad-doc:build  [local cache]

    ×  nx run utils:build
       > @secretflow/utils@0.0.1 build D:\sunbo\Haier\src\secretflow\frontend\secretpad-frontend\packages\utils
> tsup src/index.ts

CLI Building entry: src/index.ts
CLI Using tsconfig: tsconfig.json
CLI tsup v6.7.0
CLI Using tsup config: D:\sunbo\Haier\src\secretflow\frontend\secretpad-frontend\packages\utils\tsup.config.js
CLI Target: esnext
CLI Cleaning output folder
ESM Build start
CJS Build start
CJS dist\index.cjs.js     2.70 KB
CJS dist\index.cjs.js.map 3.77 KB
CJS ⚡️ Build success in 68ms
ESM dist\index.esm.js     1.62 KB
ESM dist\index.esm.js.map 3.58 KB
ESM ⚡️ Build success in 69ms
TSC Generating .d.ts
Error: spawn tsc ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
 ELIFECYCLE  Command failed with exit code 1.

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————— 

 >  NX   Ran target build for 4 projects (9s)

    √    1/2 succeeded [1 read from cache]

    ×    1/2 targets failed, including the following:
         - nx run utils:build

 ELIFECYCLE  Command failed with exit code 1.

**Comment by Chrisdehe** [comment]
@littlegirlpppp 
看起来是环境问题导致的，请参考这个文档配置一下
https://stackoverflow.com/questions/27688804/how-do-i-debug-error-spawn-enoent-on-node-js

**Comment by littlegirlpppp** [comment]
不大 了解 这块  可能 有更详细的 方案   如果是环境不对的话   pnpm dev 是 没有问题的

**Comment by zimu-yuxi** [comment]
请确保系统上已安装TypeScript。您可以通过在终端中运行命令tsc-v来检查这一点。如果没有安装TypeScript，您可以使用像npm或yarn这样的包管理器来安装它。

**Comment by tonywu6** [comment]
@littlegirlpppp 

可以复现这个问题

有留意到你在用 Windows，目前我们的构建系统对 Windows 的支持不是很好

1. 尝试：如果将 `tooling\tsup\index.js` 文件中第 18 行

    https://github.com/secretflow/secretpad-frontend/blob/ab60282c609fa6f847c6bfb44e8c7968eb5ca792/tooling/tsup/index.js#L18

    改为

    ```ts
          'tsc.cmd',
    ```

    然后再进行 `pnpm build` ，构建能成功吗？

2. 在 Windows 上开发目前推荐使用 WSL (Windows Subsystem for Linux) 来在 Windows 上使用 Linux 中的命令

    [如何使用 WSL 在 Windows 上安装 Linux](https://learn.microsoft.com/zh-cn/windows/wsl/install)

    [VS Code: Developing in WSL](https://code.visualstudio.com/docs/remote/wsl)

**Comment by littlegirlpppp** [comment]
'tsc.cmd',  构建成功   生成的dist
