### ISSUE TITLE
前端的研发中心中组件画布是用的什么插件或者组件，能告知下吗

### ISSUE THREAD

**Issue by mkcmgl** [secretflow/secretpad-frontend#16]
### Issue Type

Others

### Source

binary

### Secretflow Version

0.6

### OS Platform and Distribution

18

### Python version

3.10

### What happend and What you expected to happen.

```shell
前端的研发中心中组件画布是用的什么插件或者组件，能告知下吗
```

### Reproduction code to reproduce the issue.

```shell
前端的研发中心中组件画布是用的什么插件或者组件，能告知下吗
```

**Comment by ian-huu** [comment]
前端代码在 https://github.com/secretflow/secretpad-frontend 仓库中，可以查看一下源码

**Comment by yinrouni** [comment]
Hi， SecretPad的画布模块底层是基于[AntV X6](https://x6.antv.antgroup.com/)。我们对于画布DAG流程编排提供一个相对通用的解决方案，具体代码实现可参考 👉 https://github.com/secretflow/secretpad-frontend/tree/main/packages/dag
