### ISSUE TITLE
画布下 PSI 单独配置时无法选择左表节点

### ISSUE THREAD

**Issue by changhr2013** [secretflow/secretpad-frontend#19]
### Description 描述

画布下使用 PSI 预置模板，在快速配置中，可以看到配置左表节点的必选选项：
<img width="1456" alt="image" src="https://github.com/secretflow/secretpad-frontend/assets/8073367/a2798fb8-7a03-4aff-a0ed-d2f013d3dd6b">
但是如果不使用快速配置，单独配置组件时，没有配置左表节点的入口，会造成 PSI 任务执行失败：
<img width="1459" alt="image" src="https://github.com/secretflow/secretpad-frontend/assets/8073367/d2a122d1-c5cd-43e0-8a31-7c4bbf0b4874">
这个左表节点似乎是 secretflow 执行任务的必选项：
<img width="944" alt="image" src="https://github.com/secretflow/secretpad-frontend/assets/8073367/f6e7f3df-d44c-4f36-85be-4d46cc358ae7">
我没有找到错过快速配置后的左表节点配置入口，想咨询下是没有加配置入口还是我找的地方不对。

### Other information 其它信息

我目前搭建使用的是 secretpad 后端 master 分支最新代码编译，secretpad 前端使用的是最新的 tag 0.6.0b0，kuscia 使用 master 主分支最新代码编译，secretflow 使用的版本是 1.5.0b0。

**Comment by Angelii** [comment]
您好，这里给您提供具体的排查思路：
1. 首先可以检查一下 psi 组件版本是否为 0.0.4 ，该版本的 psi 组件包含了左表节点配置项：
![image](https://github.com/secretflow/secretpad-frontend/assets/27258415/a905fa47-68e2-4780-99b5-9ef509c1d74e)

2. 确保版本无误：
SecretPad 前后端—v0.6.0b0
SecretFlow—v1.5.0b0
SPU—v0.9.0b1
Kuscia—v0.7.0b0
SCQL—v0.6.0b1
TrustedFlow—v0.2.0b0

3. 如果是想快速使用 psi 的最新能力，可以移步官网下载最新的部署包，避免版本带来的问题：https://www.secretflow.org.cn/zh-CN/docs/secretpad/latest/mvp-platform

**Comment by changhr2013** [comment]
@Angelii 感谢，这是我的问题，因为 secretpad 后端代码我们也在开发，合并代码后，老版本的 config 下的 component 配置文件没有及时更新。
