### ISSUE TITLE
跨网进入节点问题

### ISSUE THREAD

**Issue by walkovernamtso** [secretflow/secretpad-frontend#3]
请教：节点和平台不在一个网络的情况，进入节点直接用平台的链接，是不是有问题呢？
这样无法在节点的安装侧，作为节点的一方，做数据管理、增加合作等

            <Button
              type="link"
              onClick={() => {
                const a = document.createElement('a');
                a.href = `/node?nodeId=${record.nodeId}`;
                a.target = '_blank';
                a.click();
              }}
            >
              进入节点
            </Button>

**Comment by UniqueMarvin** [comment]
你好，
1. 如果平台和节点不在一个网络，那么是需要手动将数据文件（csv文件）放在节点机器的指定目录上的，然后再通过平台去添加（流程详见：https://www.secretflow.org.cn/docs/quickstart/fn9h9yqoievouz2a#G7LaM）
2. 现在版本的secretpad是体验版本，没有节点侧平台，是在中心侧模拟了节点侧的平台。后续我们会在节点侧也部署一个平台容器的作为节点平台。

**Comment by walkovernamtso** [comment]
了解了，谢谢
